---
- name: setup baremetal flavor
  hosts: undercloud
  tasks:
    - name: setup flavors
      shell: >
          source {{ instack_user_home }}/stackrc;
          openstack flavor create --id auto --ram 4096 --disk 40 --vcpus 1 baremetal;
          openstack flavor set --property "cpu_arch"="x86_64" --property "capabilities:boot_option"="local" baremetal;