- name: Group hosts by post action - update
  hosts: undercloud:overcloud
  gather_facts: no
  tasks:
    - group_by: key="update"
      when: installer.updates is defined and
            installer.updates.enabled|bool

- name: Update the Undercloud
  gather_facts: no
  hosts: update:!overcloud
  tasks:
    - name: repolist
      sudo: yes
      command: yum -d 7 repolist

    - name: update packages
      sudo: yes
      register: yum_update_result
      yum: name=* state=latest

    - name: fail when no package has been updated
      fail: msg="Failed, no package has been updated on the undercloud"
      when: not yum_update_result.changed|bool
