---
- name: reboot
  sudo: no
  local_action:
        wait_for_ssh reboot_first=true host={{ hostvars[inventory_hostname].ansible_ssh_host }} user={{ hostvars[inventory_hostname].ansible_ssh_user }} key={{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}

- name: reboot_rdo_manager
  sudo: no
  local_action:
        wait_for_ssh
          reboot_first=true
          ssh_opts="-F ../../../ssh.config.ansible"
          host="{{ ansible_ssh_host }}"
          user="root"
          key="{{ ansible_ssh_private_key_file }}"
          sudo=false
  notify:
    - Check instance uptime

- name: Wait for libvirt guest to stop
  sudo: no
  wait_for: host={{hostvars[inventory_hostname].ansible_fqdn }} port=22
            state=stopped delay=5 timeout=300
  delegate_to: libvirt_host
  register: host_stopped
  changed_when: True
  failed_when: False
  notify:
    - Check instance uptime
    - Print instance uptime

- name: print host stopped register
  debug: var=host_stopped

- name: Wait for libvirt guest to come back
  sudo: no
  wait_for: host={{hostvars[inventory_hostname].ansible_fqdn }} port=22
            delay=10 timeout=600
  delegate_to: libvirt_host

- name: Wait after ssh service is back
  pause: seconds=120

- name: Check instance uptime
  command: uptime
  register: uptime

- name: Print instance uptime
  debug: var=uptime.stdout_lines

# this workaround has to be applied here, if ansible gets to reload facts with this file in place
# it will get a completely invalid ansible_distribution_version and the only way to classify the node
# will be with the group, all other test on version variables will fail
- name: Fix centos naming scheme
  lineinfile: dest=/etc/redhat-release regexp=7.0.[0-9]* line='CentOS Linux release 7.0 (Core)'
  when: ansible_distribution == 'CentOS' and ansible_distribution_version|int == 7

- name: Reload facts
  action: setup

- name: Yum clean all
  command: yum clean all

- name: Yum repolist
  command: yum repolist
  ignore_errors: yes

- name: restart network
  service: name=network state=restarted
  notify:
    - Reload facts
