---
- name: Install ksgen
  command: "{{ ansible_env.HOME }}/.venv/bin/python setup.py develop
           chdir={{ ansible_env.HOME }}/khaleesi/tools/ksgen"


- name: create group dir
  file: state=directory path={{ ansible_env.HOME }}/staypuft-install-groups/group1

- name: copy Vagrant file on install group
  copy: src=Vagrantfile dest={{ ansible_env.HOME}}/staypuft-install-groups/group1

- name: copy useful exports for cli debugging
  template: src=vagrant-exports.j2 dest={{ ansible_env.HOME}}/staypuft-install-groups/group1/vagrant-exports

- name: Run ksgen
  command: "{{ ansible_env.HOME }}/.venv/bin/ksgen
              --config-dir={{ ansible_env.HOME }}/khaleesi-settings/settings generate
              --rules-file={{ ansible_env.HOME }}/khaleesi-settings/rules/staypuft-rhos-vagrant.yml
              --product-version-workaround=rhel-6.5
              --product-version-repo={{ product.repo_type }}
              --workarounds=enabled
              --distro=rhel-6.5
              ksgen_settings.yml
              chdir={{ ansible_env.HOME }}/staypuft-install-groups/group1"


- name: pre create vagrant ansible inventory dir
  file:  path={{ansible_env.HOME}}/staypuft-install-groups/group1/.vagrant/provisioners/ansible/inventory/ state=directory

- name: make group vars available to inner ansible
  command: cp -a {{ansible_env.HOME}}/khaleesi/group_vars {{ansible_env.HOME}}/staypuft-install-groups/group1/.vagrant/provisioners/ansible/inventory/

- name: Run vagrant
  command: "vagrant up foreman chdir={{ ansible_env.HOME }}/staypuft-install-groups/group1"
  environment: vagrant_environment

- name: Detect Foreman IP
  shell: 'vagrant ssh -c "ip a show to 10.0.0.0/8 primary" | grep inet | sed -e "s/[[:blank:]]*inet \(.*\)\/[0-9]* brd .* scope global \(.*\)/Public IP address is \1 on interface \2/"'
  args:
      chdir: "{{ ansible_env.HOME }}/staypuft-install-groups/group1"
  register: foreman_public_ip
  environment: vagrant_environment

- name: Show staypuft VM public ip
  debug: msg="{{ foreman_public_ip.stdout }}"

- name: echo foreman ip to file
  shell: echo "forman ip address, {{ foreman_public_ip.stdout }}" >  /tmp/STAYPUFT_README

- name: echo username and password
  shell: echo "user = admin, password =  redhat" >> /tmp/STAYPUFT_README

- name: Get Staypuft environment information
  fetch: src=/tmp/STAYPUFT_README dest=~/KHALEESI_STAYPUFT_README flat=yes
