---
- name: Acquire nodes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get nodes
      centosci:
           request="get"
           url="{{ provisioner.url }}"
           ver="{{ provisioner.distro.version }}"
           arch="{{ provisioner.arch }}"
           count="{{ provisioner.node_count }}"
      retries: 5
      delay: 60
      register: provisioned_nodes

    - name: Save SSID to file
      shell: >
          echo "{{ provisioned_nodes.ssid }}" > {{ lookup('env', 'PWD') }}/centosci_ssid

    - name: ensure correct key_file permission
      file: path={{ provisioner.key_file }} mode=0600

    - name: Add created hosts to rdo-manager host list
      add_host:
        name="{{ item.name }}"
        groups="provisioned"
        ansible_fqdn="{{ item.hostname }}"
        ansible_ssh_user="{{ provisioner.remote_user }}"
        ansible_ssh_private_key_file="{{ provisioner.key_file }}"
        ansible_ssh_host="{{ item.hostname }}"
      with_items: provisioned_nodes.hosts
      when: installer.type in ['rdo-manager']

    - name: Add created hosts to packstack host list
      add_host:
        name="{{ item.name }}"
        groups="provisioned, controller, network, compute, openstack_nodes"
        ansible_fqdn="{{ item.hostname }}"
        ansible_ssh_user="{{ provisioner.remote_user }}"
        ansible_ssh_private_key_file="{{ provisioner.key_file }}"
        ansible_ssh_host="{{ item.hostname }}"
      with_items: provisioned_nodes.hosts
      when: installer.type in ['packstack']

- name: wait for hosts to get reachable
  hosts: centosci
  gather_facts: no
  max_fail_percentage: 0
  tasks:
    - local_action:
        module: wait_for_ssh host={{ hostvars[inventory_hostname].ansible_ssh_host }} user=root key={{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}
      sudo: no

- name: Update network interfaces on nodes - OpenStack
  hosts: openstack_nodes
  gather_facts: yes
  max_fail_percentage: 0
  sudo: no
  tasks:
    - name: updating host short name
      set_fact: inventory_hostname_short="controller"
      when: installer.type in ['packstack']

    - name: Setup networking (interfaces)
      template:
            src: ../templates/ifcfg-interface.j2
            dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.value.label }}
            owner: root
            group: root
            mode: 644
      with_dict:
          provisioner.nodes[inventory_hostname_short].network.interfaces
      register: update_ifcfgs
      when: installer.type in ['packstack']

    #TODO(tkammer): write this better by fixing the upstream module to provide the private IP properly
    - name: update IP address of eth1 interface
      lineinfile:
          dest: /etc/sysconfig/network-scripts/ifcfg-eth1
          regexp: IPADDR=
          line: "IPADDR={{ hostvars[inventory_hostname].eth1_interface_ip }}"
      register: update_ifcfg1
      when: installer.type in ['packstack']

    - name: reboot after networking update
      local_action:
        module: wait_for_ssh host={{ hostvars[inventory_hostname].ansible_ssh_host }} user=root key={{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}
        sudo: no
      when: installer.type in ['packstack']


