- name: get ip addresses of guests
  shell: >
   cat  /var/lib/libvirt/dnsmasq/default.leases  | awk -F " " '{print $3}' > /tmp/leases
  register: result

- name: get ip addresses of guests
  shell: >
   cat  /var/lib/libvirt/dnsmasq/default.leases  | awk -F " " '{print $3}' | tr '\n' ', '
  register: result


- name: print ip addresses of guests
  debug: msg={{result.stdout_lines}}

- name: Create ssh key if one does not exist
  # this will not overwrite an existing key
  user: name=root generate_ssh_key=yes
  sudo: yes
  sudo_user: root

- name: add id_rsa to authorized_keys
  shell: cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
  sudo: yes
  sudo_user: root

- name: ensure sshpass
  yum: name=sshpass state=latest

- name: add ssh key to guests
  shell: >
   for i in `cat /tmp/leases`; do sshpass -p vagrant ssh-copy-id vagrant@$i; done
  ignore_errors: true