---
#CENTOS

- name: Ensure centos-release
  yum: name=centos-release state=present

- name: Create the CentOS Repositories
  template: src=CentOS-Base.repo.j2 dest=/etc/yum.repos.d/CentOS-Base.repo


- name: Create the EPEL Repository
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo


