---
- name: install libvirt host rpm dependencies
  yum: name={{ item }} state=present
  with_items:
    - virt-install
    - genisoimage

- name: download cloud image
  get_url: >
    url="{{ distro.images[distro.name][distro.version].remote_file_server }}{{ distro.images[distro.name][distro.version].guest_image_name }}"
    dest="{{ base_dir }}/{{ distro.images[distro.name][distro.version].guest_image_name }}"

- name: resize cloud image
  command: qemu-img resize "{{ base_dir }}/{{ distro.images[distro.name][distro.version].guest_image_name }}" {{cloud_image_resize}}

- name: get meta-data template
  template: src=meta-data.j2 dest="{{ base_dir }}/meta-data"

- name: get user-data template
  template: src=user-data.j2 dest="{{ base_dir }}/user-data"

- name: generate cloud-init iso
  command: genisoimage -output "{{ base_dir }}/{{cloud_init_iso_name}}" -volid cidata -joliet -rock "{{ base_dir }}/meta-data" "{{ base_dir }}/user-data"

- name: copy images to /var/lib/libvirt/images
  command: cp {{item}} /var/lib/libvirt/images/
  with_items:
    - "{{ base_dir }}/{{ distro.images[distro.name][distro.version].guest_image_name }}"
    - "{{ base_dir }}/{{cloud_init_iso_name}}"

- name: import and launch image
  shell: >
    virt-install \
      --import \
      --name instack \
      --ram {{instance_ram}} \
      --vcpus {{instance_vcpu}} \
      --disk "{{hypervisor_image_path}}{{ distro.images[distro.name][distro.version].guest_image_name }}" \
      --disk {{hypervisor_image_path}}{{ cloud_init_iso_name }},device=cdrom \
      --network bridge=virbr0 \
      --noautoconsole

# - name: print result of instance start
#   debug: var=result

- name: Pause {{boot_timeout}} seconds for instance to boot
  pause: seconds={{boot_timeout}}
