---
- name: Ensure foreman and puppet repos are enabled
  ini_file: dest=/etc/yum.repos.d/{{ item.repo }}.repo
            section={{ item.section }}
            option={{ item.option }}
            value={{ item.value }}
  with_items:
    - { repo: foreman, section: foreman, option: enabled, value: 1 }
    - { repo: foreman, section: foreman-plugins, option: enabled, value: 1 }
    - { repo: puppetlabs, section: puppetlabs-products, option: enabled, value: 1 }
    - { repo: puppetlabs, section: puppetlabs-deps, option: enabled, value: 1 }
