---
- name: Patch rpm
  hosts: local
  roles:
   - patch_rpm

- include: provision.yml

- name: Create local repo for patched rpm
  hosts: controller
  tasks:
    - name: Install release tool
      sudo: yes
      command: "yum localinstall -y {{ product.rpm }}"

    - name: Execute rhos-release for packstack poodle/puddle
      sudo: yes
      command: "rhos-release {{ product.version.major }} {{ product.repo.rhos_release.extra_args|join(' ') }}"

    - name: Install createrepo
      sudo: yes
      yum:  name=createrepo state=present

    - name: create repo folder
      file: path=/home/{{ ansible_ssh_user }}/dist-git/ state=directory

    - name: copy the generated rpms
      copy: src={{ item }} dest=/home/{{ ansible_ssh_user }}/dist-git/{{ patch.dist_git.name }}/
      with_fileglob:
       - "{{ lookup('env', 'PWD') }}/generated_rpms/*.rpm"

    - name: Setup repository for patched rpm
      sudo: yes
      template: "src={{ lookup('env', 'PWD') }}/roles/patch_rpm/templates/patched_rpms.j2 dest=/etc/yum.repos.d/patched_rpms.repo"
      when: "{{ hostvars['localhost'].rpm_build_rc }} == 0"

    - name: Create local repo for patched rpm
      sudo: yes
      shell: "createrepo /home/{{ ansible_ssh_user }}/dist-git/{{ patch.dist_git.name }}"
      when: "{{ hostvars['localhost'].rpm_build_rc }} == 0"

- include: install.yml
- include: test.yml
