---
- name: Get nodes from nova
  hosts: local
  gather_facts: False
  roles:
    - { role: get_r_nodes }
  tags:
    - provision

- name: Set facts for hosts
  hosts: packstack
  gather_facts: False
  roles:
    - { role: set_facts }
    - { role: wait_for_hosts }
  tags:
    - provision

- name: Set facts for hosts
  hosts: openstack_nodes:&tempest
  user: "{{ tempest_remote_user }}"
  gather_facts: False
  roles:
    - { role: set_facts }
    - { role: wait_for_hosts }
  tags:
    - provision
