---
# determine provisioner and whether or not to skip
- include: group_by_provision.yml

# provision
- include: tripleo/beaker-provision.yml

- include: rdo-manager-undercloud.yml
- include: rdo-manager-overcloud.yml

- name: unregister rhsm
  hosts: all:!localhost:!overcloud
  sudo: yes
  roles:
    - { role: linux/rhsm, when: product.repo_type_override is defined and product.repo_type_override == 'rhsm' }

- name: Gather Logs
  hosts: all:!localhost
  sudo: yes
  roles:
    - collect_logs
