---
- include: group_by.yml ansible_ssh_user=root

# Provides CentOS repos if absent
- name: CentOS RDO prep
  hosts: undercloud:&CentOS
  vars:
    - ansible_ssh_user: root
  roles:
    - { role: linux/centos, yum_update: false }

# Provides EPEL
- name: RHEL RDO prep
  hosts: undercloud:&RedHat
  vars:
    - ansible_ssh_user: root
  roles:
    - { role: linux/rhel/rdo, yum_update: false}

# Provides rhos-release
- name: RHEL RHOS prep
  hosts: undercloud:&RedHat
  vars:
    - ansible_ssh_user: root
  roles:
    - { role: linux/rhel/rhos, product_override_version: "6", yum_update: false,
          when: product.repo_type_override is not defined }

# Provides rhsm repos
- name: RHEL RHOS prep
  hosts: undercloud:&RedHat
  vars:
    - ansible_ssh_user: root
  roles:
    - { role: linux/rhel/rhos, product_override_version: 6.0, product_repo_type_override: "rhsm", yum_update: false,
          when: product.repo_type_override is defined and product.repo_type_override == 'rhsm'}

# Collect performance data, etc.
- name: Linux common prep
  hosts: undercloud
  vars:
    - ansible_ssh_user: root
  roles:
    - { role: linux-common }

# Provides rdo and delorean repos
- name: Setup dependencies on nodes (rdo)
  hosts: undercloud
  vars:
    - ansible_ssh_user: root
  roles:
      - { role: product/rdo/rhel, yum_update: false }

