---
- name: install rdo gpg key
  copy: src=RPM-GPG-KEY-RDO-Juno dest=/etc/pki/rpm-gpg/ owner=root group=root
  when: product.version == "juno"

- name: install rdo gpg key
  copy: src=RPM-GPG-KEY-RDO-Icehouse dest=/etc/pki/rpm-gpg/ owner=root group=root
  when: product.version == "icehouse"

- name: install rdo gpg key
  copy: src=RPM-GPG-KEY-RDO-Havana dest=/etc/pki/rpm-gpg/ owner=root group=root
  when: product.version == "havana"

- name: yum install rdo-release
  yum: name="{{ product.rpm[ ansible_distribution ] }}" state=present     #"
  when: product.repo_type in ('production', 'stage', 'delorean')
  retries: 3
  delay: 30
  register: rdo_release_install_result
  until: rdo_release_install_result.rc == 0

- name: Create the upstream delorean repositories for Fedora RDO
  get_url: url="{{ product.repo[product.repo_type][ansible_distribution][ansible_distribution_version] }}"/current/delorean.repo
            dest=/etc/yum.repos.d/rdo-trunk-release.repo
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type == 'delorean' and product.repo.delorean_pin_version is not defined

- name: Create the pinned upstream delorean repositories for Fedora RDO
  get_url: url="{{ product.repo[product.repo_type][ansible_distribution][ansible_distribution_version] }}"/"{{product.repo.delorean_pin_version}}"/delorean.repo
            dest=/etc/yum.repos.d/rdo-trunk-release.repo 
            mode=0644
  notify:
    - Yum clean all
  when: product.repo_type in ['delorean'] and product.repo.delorean_pin_version is defined

- name: set baseurl for rdo if stage
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^baseurl=
    line="baseurl={{ product.repo[product.repo_type][ansible_distribution][ansible_distribution_version] }}"
  when: product.repo_type == 'stage'
  notify:
    - Yum clean all

- name: disable gpgcheck for rdo if not distribution-repo
  lineinfile:
    dest=/etc/yum.repos.d/rdo-release.repo
    regexp=^gpgcheck=1
    line=gpgcheck=0
  when: product.repo_type not in ('production', 'distribution')

- name: List available yum repositories
  command: yum -d 7 repolist
  register: result

- name: Print repolist
  debug: var=result.stdout_lines

